name: Keycloak CI

on:
  push:
    branches-ignore:
      - main
      - dependabot/**
  pull_request:
  schedule:
    - cron: 0 20,23,2,5 * * *
  workflow_dispatch:

env:
  DEFAULT_JDK_VERSION: 17
  DEFAULT_JDK_DIST: temurin
  SUREFIRE_RERUN_FAILING_COUNT: 2

concurrency:
  # Only cancel jobs for PR updates
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:

  conditional:
    name: Check conditional workflows and jobs
    if: github.event_name != 'schedule' || github.repository == 'keycloak/keycloak'
    runs-on: ubuntu-latest
    outputs:
      ci: ${{ steps.conditional.outputs.ci }}
      sssd: ${{ steps.conditional.outputs.sssd }}
    steps:
      - uses: actions/checkout@v3

      - id: conditional
        uses: ./.github/actions/conditional

  build:
    name: Build
    if: needs.conditional.outputs.ci == 'true'
    runs-on: ubuntu-latest
    needs: conditional
    steps:
      - uses: actions/checkout@v3

      - name: Build Keycloak
        uses: ./.github/actions/build-keycloak

  sssd-unit-tests:
    name: SSSD
    runs-on: ubuntu-latest
    needs:
      - conditional
      - build
    timeout-minutes: 30
    steps:
      - name: checkout
        if: ${{ needs.conditional.outputs.sssd == 'true' }}
        uses: actions/checkout@v3

      - id: integration-test-setup
        if: ${{ needs.conditional.outputs.sssd == 'true' }}
        name: Integration test setup
        uses: ./.github/actions/integration-test-setup

      - name: Run tests
        if: ${{ needs.conditional.outputs.sssd == 'true' }}
        run: .github/scripts/run-ipa.sh "${{ github.workspace }}"

  check-set-status:
    name: Set check conclusion
    needs:
      - sssd-unit-tests
    runs-on: ubuntu-latest
    outputs:
      conclusion: ${{ steps.check.outputs.conclusion }}

    steps:
      - uses: actions/checkout@v3

      - id: check
        uses: ./.github/actions/checks-success

  check:
    name: Status Check - Keycloak CI
    if: always() && ( github.event_name != 'schedule' || github.repository == 'keycloak/keycloak' )
    needs:
      - conditional
      - check-set-status
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check status
        uses: ./.github/actions/checks-job-pass
        with:
          required: ${{ needs.conditional.outputs.ci }}
          conclusion: ${{ needs.check-set-status.outputs.conclusion }}
